routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','BerandaController@index')->name('home');
Route::get('/add-to-cart/{id}','BerandaController@addTocart');
Route::post('/add-to-cart', 'BerandaController@addCart');
Route::get('/product/category/{slug}','BerandaController@category');
//Route::get('/product/detail/{id}','BerandaController@detail');
Route::get('/product/detail/{id}','BerandaController@detail');

Route::get('/shopping-cart','CartController@index');
Route::get('/shopping-cart/update/{id}', 'CartController@update');
Route::get('/shopping-cart/kurangi/{id}', 'CartController@kurangi');
Route::delete('/shopping-cart/delete/{id}', 'CartController@delete');
Route::get('/shopping-cart/destroy', 'CartController@destroy');

Route::get('/list-product', 'BerandaController@listProduct');

Route::get('/change-password', 'BerandaController@changePassword');
Route::post('/change-password', 'BerandaController@updatePassword')->name('updatePassword');

Route::get('/about', 'BerandaController@about');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('tes',function(){
//    return view('layouts.master');
// });


Route::group(['middleware' => 'auth'], function (){
    Route::get('/shopping-cart/checkout','CartController@checkout');
    Route::post('/shopping-cart/bayar','CartController@bayar');
    Route::post('/cek-ongkir','CartController@ongkir')->name('cek_ongkir');
    Route::get('/cek-ongkir','CartController@congkir');
    Route::get('/invoice','InvoiceController@index');
    Route::get('/invoice/list','InvoiceController@list');
    Route::get('/invoice/detail/{id}','InvoiceController@detail')->name('invoice.detail');

    Route::get('/confirm/{id}', 'ConfirmController@index')->name('confirm.index');
    Route::post('/confirm/store','ConfirmController@store')->name('confirm.store');

    Route::get('/confirmAdmin','ConfirmAdminController@index')->name('confirmAdmin');
    Route::get('/confirmAdmin/detail/{id}','ConfirmAdminController@detail');
    Route::get('/confirmAdmin/terima/{order_id}','ConfirmAdminController@terima')->name('confirmAdmin.terima');
    Route::get('/confirmAdmin/tolak/{order_id}','ConfirmAdminController@tolak')->name('confirmAdmin.tolak');
		
    Route::get('/paymentConfirm','PaymentConfirmController@index')->name('paymentConfirm');
    Route::get('/paymentConfirm/detail/{id}','PaymentConfirmController@detail');
    Route::get('/paymentConfirm/terima/{order_id}','PaymentConfirmController@terima')->name('paymentConfirmterima');
		Route::get('/paymentConfirm/tolak/{order_id}','PaymentConfirmController@tolak')->name('paymentConfirmtolak');
		
    Route::get('/order','OrderController@index');
    Route::get('/order/detail/{id}','OrderController@detail');
    Route::get('/order/pdf','OrderController@exportPDFALL')->name('order.pdf');
    Route::get('/order_lunas/pdf','OrderController@exportPDF')->name('order_lunas.pdf');
    Route::get('/order/excel','OrderController@exportExcel')->name('order.excel');
    Route::get('/order_lunas/excel','OrderController@exportExcelPaid')->name('order_lunas.excel');

    Route::resource('product','ProductController');
    Route::get('productAdmin/detail/{id}','ProductController@detail')->name('product.detail');
		Route::resource('category','CategoryController');
		
		Route::get('/pos', 'PosController@index');
		Route::post('/pos', 'PosController@store')->name('pos.store');
		Route::get('/pos/data', 'PosController@data')->name('pos.data');

		Route::post('/cart/getData', 'PosCartController@getData')->name('cart.getData');
		Route::post('/cart/check', 'PosCartController@check')->name('cart.check');
		Route::post('/cart/add', 'PosCartController@add')->name('cart.add');
		Route::get('/cart/destroy', 'PosCartController@destroy')->name('cart.destroy');
		Route::get('/cart/getTotal', 'PosCartController@getTotal')->name('cart.getTotal');
		Route::post('/cart/delete', 'PosCartController@delete')->name('cart.delete');
		Route::post('/cart/checkCartItem', 'PosCartController@checkCartItem')->name('cart.checkCartItem');
		Route::post('/cart/update', 'PosCartController@update')->name('cart.update');

		Route::resource('user', 'UsersController');
	});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $fillable = ['name','slug'];
    protected $hidden = ['created_at','updated_at'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use function GuzzleHttp\Psr7\str;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $title = "Master Categories";
        $categories = Category::orderBy('name','ASC')->get();
        return view('categories.index2', compact('title', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Create Category";
        return view('categories.create2', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $request['slug'] = str_slug($request->get('name'), '-');

        $category = new Category();
        $category->name = $request->get('name');
        $category->slug = str_slug($request->get('name'),'-');
        $category->save();

        return redirect()->back()->with('status','Anda berhasil menambahkan kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = 'Edit Category';
        $category = Category::findOrFail($id);
        return view('categories.edit2',compact('category', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name = $request->get('name');
        $category->slug = str_slug($request->get('name'),'-');
        $category->update();

        return redirect(url('/category'))->with('status','Anda berhasil mengupdate kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->back()->with('status','Anda berhasil menghapus kategori');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.master')

@section('top')
@endsection

@section('content')
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $title }}</h3>
            </div>

            <div class="box-header with-border">
                @if(session('status'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <i class="icon fa fa-check"></i> Success! &nbsp;
                        {{ session('status') }}
                    </div>
                @endif
            </div>

            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post" action="{{ route('category.store')  }}" enctype="multipart/form-data">
                @csrf
                <div class="box-body">

                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" value="{{ old('name') }}" autofocus required>
                    </div>

                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </div>
@endsection


@section('top')
@endsection

resources/views/categories/create2.blade.php
@extends('layouts.master-back')	

@section('content')
<div class="card">
	<div class="card-body">
		<div class="row align-items-center">
			<div class="col">
				<h4 class="header-title">
					<i class="ti-pencil-alt text-primary"></i> &ensp;
					Tambah Data Kategori
				</h4>
			</div>
			<div class="col text-right act-button">
				<a href="{{ url('/category') }}" class="btn btn-sm btn-danger">
					Kembali
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-lg-8">
				<form method="post" action="{{ route('category.store')  }}" enctype="multipart/form-data">
					@csrf
					<div class="form-group">
						<label for="" class="form-control-label">Nama Kategori : </label>
						<input type="text" name="name" id="name" class="form-control" placeholder="Masukan Nama Kategori..." value="{{ old('name') }}" autofocus required>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-sm btn-success">
							Tambah Data
						</button>
						<button type="reset" class="btn btn-sm btn-danger">
							Reset Input
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function() {
		$('#name').focus();
	});
</script>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.master')

@section('top')
@endsection

@section('content')
<div class="col-md-6">
	<!-- general form elements -->
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">{{ $title }}</h3>
		</div>

		<div class="box-header with-border">
			@if(session('status'))
			<div class="alert alert-success alert-dismissible">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<i class="icon fa fa-check"></i> Success! &nbsp;
				{{ session('status') }}
			</div>
			@endif
		</div>

		<!-- /.box-header -->
		<!-- form start -->
		<form role="form" method="post" action="{{ route('category.update', ['id' => $category->id])  }}"
			enctype="multipart/form-data">
			@csrf
			@method('PUT')
			<div class="box-body">

				<div class="form-group">
					<label>Name</label>
					<input type="text" class="form-control" id="name" name="name" placeholder="Enter name"
						value="{{ $category->name }}" autofocus required>
				</div>

			</div>
			<!-- /.box-body -->

			<div class="box-footer">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</form>
	</div>
	<!-- /.box -->
</div>
@endsection


@section('top')
@endsection

resources/views/categories/edit2.blade.php
@extends('layouts.master-back')

@section('content')
<div class="card">
	<div class="card-body">
		<div class="row align-items-center">
			<div class="col">
				<h4 class="header-title">
					<i class="ti-pencil-alt text-warning"></i> &ensp;
					Edit Data Kategori
				</h4>
			</div>
			<div class="col text-right act-button">
				<a href="{{ url('/category') }}" class="btn btn-sm btn-danger">
					Kembali
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-lg-8">
				<form role="form" method="post" action="{{ route('category.update', ['id' => $category->id])  }}"
					enctype="multipart/form-data">
					@csrf
					@method('PUT')
					<div class="form-group">
						<label for="" class="form-control-label">Nama Kategori : </label>
						<input type="text" name="name" id="name" class="form-control" placeholder="Masukan Nama Kategori..."
							value="{{ $category->name }}" autofocus required>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-sm btn-success">
							Simpan Perubahan
						</button>
						<button type="reset" class="btn btn-sm btn-danger">
							Reset Input
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function () {
		$('#name').focus();
	});
</script>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.master')

@section('top')
    <!-- DataTables -->
    <link rel="stylesheet" href=" {{ asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }} ">
@endsection

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">{{ $title }}</h3>
                </div>


                @if(session('status'))
                    <div class="box-header">
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <i class="icon fa fa-check"></i> Success! &nbsp;
                            {{ session('status') }}
                        </div>
                    </div>
            @endif


            <!-- /.box-header -->
                <div class="box-body">
                    <table id="categories" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th width="10px">ID</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th width="10px"></th>
                            <th width="300px"></th>
                        </tr>
                        </thead>

                        @php
                        $no = 1;
                        @endphp

                        @foreach($categories as $category)
                            <tbody>
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td> {{ $category->name }}</td>
                                <td><a class="btn bg-teal-active"><b>{{ $category->slug }}</b></a></td>
                                <td>
                                    <a href="{{ route('category.edit', ['id' => $category->id]) }}" class="btn bg-navy">Edit</a>
                                </td>
                                <td>
                                    <form action="{{ route('category.destroy', ['id' => $category->id]) }}" method="post" onsubmit="return confirm('Delete this posts permanently ?')">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn bg-red-active" value="Delete">
                                        {{--<button class="btn btn-danger" type="submit">Delete</button>--}}
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        @endforeach

                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th width="10px"></th>
                            <th width="300px"></th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
@endsection


@section('bot')
    <!-- DataTables -->
    <script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }} "></script>
    <script src="{{ asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }} "></script>

    <script>
        $(function () {
            // $('#categories').DataTable()
            $('#categories').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false,
                // 'processing'  : true,
                // 'serverSide'  : true,

            })
        })
    </script>
@endsection

resources/views/categories/index2.blade.php
@extends('layouts.master-back')

@section('content')
<div class="card">
	<div class="card-body">
		<div class="row align-items-center">
			<div class="col">
				<h4 class="header-title">
					<i class="ti-view-list-alt"></i> &ensp;
					Data Kategori
				</h4>
			</div>
			<div class="col text-right act-button">
				<a href="{{ url('/category/create') }}" class="btn btn-sm btn-primary">
					Tambah Data
				</a>
			</div>
		</div>
		<div class="row mt-3">
			<div class="col-12">
				<div class="table-responsive">
					<!-- Projects table -->
					<table class="table align-items-center table-flush" id="table1">
						<thead class="thead-light">
							<tr>
								<th scope="col">ID</th>
								<th scope="col">Nama</th>
								<th scope="col">Slug</th>
								<th scope="col"></th>
							</tr>
						</thead>
						<tbody>
							@foreach ($categories as $item)
							<tr>
								<td>{{ $loop->iteration }}</td>
								<td>{{ $item->name }}</td>
								<td><a class="badge badge-info text-white"><b>{{ $item->slug }}</b></a></td>
								<td class="text-right">
									<div class="dropdown">
										<a class="btn btn-sm btn-default btn-icon-only" href="#" role="button"
											data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<i class="ti-more"></i>
										</a>
										<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
											<a class="dropdown-item" href="{{ route('category.edit', ['id' => $item->id]) }}">Edit Data</a>
											<a class="dropdown-item" href="#"
												onclick="event.preventDefault(); document.getElementById('delete{{ $loop->iteration }}').submit();">Hapus
												Data</a>
										</div>

										<form action="{{ route('category.destroy', ['id' => $item->id]) }}" method="post"
											id="delete{{ $loop->iteration }}" onsubmit="">
											@csrf
											@method('DELETE')
										</form>
									</div>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function() {
		$('#table1').DataTable();
	});
</script>
@endsection