routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','BerandaController@index')->name('home');
Route::get('/add-to-cart/{id}','BerandaController@addTocart');
Route::post('/add-to-cart', 'BerandaController@addCart');
Route::get('/product/category/{slug}','BerandaController@category');
//Route::get('/product/detail/{id}','BerandaController@detail');
Route::get('/product/detail/{id}','BerandaController@detail');

Route::get('/shopping-cart','CartController@index');
Route::get('/shopping-cart/update/{id}', 'CartController@update');
Route::get('/shopping-cart/kurangi/{id}', 'CartController@kurangi');
Route::delete('/shopping-cart/delete/{id}', 'CartController@delete');
Route::get('/shopping-cart/destroy', 'CartController@destroy');

Route::get('/list-product', 'BerandaController@listProduct');

Route::get('/change-password', 'BerandaController@changePassword');
Route::post('/change-password', 'BerandaController@updatePassword')->name('updatePassword');

Route::get('/about', 'BerandaController@about');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('tes',function(){
//    return view('layouts.master');
// });


Route::group(['middleware' => 'auth'], function (){
    Route::get('/shopping-cart/checkout','CartController@checkout');
    Route::post('/shopping-cart/bayar','CartController@bayar');
    Route::post('/cek-ongkir','CartController@ongkir')->name('cek_ongkir');
    Route::get('/cek-ongkir','CartController@congkir');
    Route::get('/invoice','InvoiceController@index');
    Route::get('/invoice/list','InvoiceController@list');
    Route::get('/invoice/detail/{id}','InvoiceController@detail')->name('invoice.detail');

    Route::get('/confirm/{id}', 'ConfirmController@index')->name('confirm.index');
    Route::post('/confirm/store','ConfirmController@store')->name('confirm.store');

    Route::get('/confirmAdmin','ConfirmAdminController@index')->name('confirmAdmin');
    Route::get('/confirmAdmin/detail/{id}','ConfirmAdminController@detail');
    Route::get('/confirmAdmin/terima/{order_id}','ConfirmAdminController@terima')->name('confirmAdmin.terima');
    Route::get('/confirmAdmin/tolak/{order_id}','ConfirmAdminController@tolak')->name('confirmAdmin.tolak');
		
    Route::get('/paymentConfirm','PaymentConfirmController@index')->name('paymentConfirm');
    Route::get('/paymentConfirm/detail/{id}','PaymentConfirmController@detail');
    Route::get('/paymentConfirm/terima/{order_id}','PaymentConfirmController@terima')->name('paymentConfirmterima');
		Route::get('/paymentConfirm/tolak/{order_id}','PaymentConfirmController@tolak')->name('paymentConfirmtolak');
		
    Route::get('/order','OrderController@index');
    Route::get('/order/detail/{id}','OrderController@detail');
    Route::get('/order/pdf','OrderController@exportPDFALL')->name('order.pdf');
    Route::get('/order_lunas/pdf','OrderController@exportPDF')->name('order_lunas.pdf');
    Route::get('/order/excel','OrderController@exportExcel')->name('order.excel');
    Route::get('/order_lunas/excel','OrderController@exportExcelPaid')->name('order_lunas.excel');

    Route::resource('product','ProductController');
    Route::get('productAdmin/detail/{id}','ProductController@detail')->name('product.detail');
		Route::resource('category','CategoryController');
		
		Route::get('/pos', 'PosController@index');
		Route::post('/pos', 'PosController@store')->name('pos.store');
		Route::get('/pos/data', 'PosController@data')->name('pos.data');

		Route::post('/cart/getData', 'PosCartController@getData')->name('cart.getData');
		Route::post('/cart/check', 'PosCartController@check')->name('cart.check');
		Route::post('/cart/add', 'PosCartController@add')->name('cart.add');
		Route::get('/cart/destroy', 'PosCartController@destroy')->name('cart.destroy');
		Route::get('/cart/getTotal', 'PosCartController@getTotal')->name('cart.getTotal');
		Route::post('/cart/delete', 'PosCartController@delete')->name('cart.delete');
		Route::post('/cart/checkCartItem', 'PosCartController@checkCartItem')->name('cart.checkCartItem');
		Route::post('/cart/update', 'PosCartController@update')->name('cart.update');

		Route::resource('user', 'UsersController');
	});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<!-- Header -->
<div class="header bg-primary pb-6">
	<div class="container-fluid">
		<div class="header-body">
			<div class="row align-items-center py-4">
				<div class="col-lg-6 col-7">
					<h6 class="h2 text-white d-inline-block mb-0">Judul</h6>
				</div>
				<div class="col-lg-6 col-5 text-right">
					<a href="#" class="btn btn-sm btn-neutral">New</a>
					<a href="#" class="btn btn-sm btn-neutral">Filters</a>
				</div>
			</div>
		</div>
	</div>
</div>

resources/views/layouts/master-back.blade.php
<!doctype html>
<html class="no-js" lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Yoshida | Baby & Sleepwear</title>
	<link rel="icon" href="{{ asset('frontend2') }}/img/favicon.png">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/font-awesome.min.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/themify-icons.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/metisMenu.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/owl.carousel.min.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/slicknav.min.css">
	<!-- amchart css -->
	<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
	<!-- others css -->
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/typography.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/default-css.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/styles.css">
	<link rel="stylesheet" href="{{ asset('backend/assets2') }}/css/responsive.css">
	<!-- modernizr css -->
	<script src="{{ asset('backend/assets2') }}/js/vendor/modernizr-2.8.3.min.js"></script>

	{{-- Other --}}

	<link rel="stylesheet" href="{{ asset('backend') }}/datatables/datatables.min.css" type="text/css">
	<link rel="stylesheet" href="{{ asset('backend') }}/lightbox2/css/lightbox.min.css" type="text/css">
	
	<link href="{{ asset('assets/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet">
	<script src="{{ asset('assets/sweetalert2/sweetalert2.min.js') }}"></script>

	<style>
		div.dataTables_wrapper div.dataTables_length select {
			width: 60px !important;
		}

		.act-button {
			margin-top: -20px !important;
		}

		select.form-control:not([size]):not([multiple]) {
			height: 44px !important;
		}
	</style>

	@yield('css')
</head>

<body>
	<!--[if lt IE 8]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
	<!-- preloader area start -->
	<div id="preloader">
		<div class="loader"></div>
	</div>
	<!-- preloader area end -->
	<!-- page container area start -->
	<div class="page-container sbar_collapsed">
		<!-- sidebar menu area start -->
		<div class="sidebar-menu">
			<div class="sidebar-header">
				<div class="logo" style="background-color: #ffffff;">
					<a href="index.html"><img src="{{ asset('frontend2') }}/logo.png" alt="logo"></a>
				</div>
			</div>
			<div class="main-menu">
				<div class="menu-inner">
					<nav>
						<ul class="metismenu" id="menu">
							<li>
								<a href="{{ url('/home') }}" aria-expanded="true"><i class="ti-home"></i><span>Halaman Utama</span></a>
							</li>
							<li>
								<a href="javascript:void(0)" aria-expanded="true"><i class="ti-pencil-alt"></i><span>Form Master</span></a>
								<ul class="collapse">
									<li><a href="{{ route('category.index') }}">Kategori</a></li>
									<li><a href="{{ route('product.index') }}">Produk</a></li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0)" aria-expanded="true"><i class="ti-shopping-cart"></i><span>Transaksi</span></a>
								<ul class="collapse">
									<li><a href="{{ url('/order') }}">Data Pemesanan</a></li>
									<li><a href="{{ url('/confirmAdmin') }}">Konfirmasi Pemesanan</a></li>
									<li><a href="{{ url('/paymentConfirm') }}">Konfirmasi Pembayaran</a></li>
								</ul>
							</li>
							@if (auth()->user()->role == 'admin')
							<li>
								<a href="{{ url('/user') }}" aria-expanded="true"><i class="ti-user"></i><span>Manajemen User</span></a>
							</li>
							@endif
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<!-- sidebar menu area end -->
		<!-- main content area start -->
		<div class="main-content">
			<!-- header area start -->
			<div class="header-area">
				<div class="row align-items-center">
					<!-- nav and search button -->
					<div class="col-md-6 col-sm-8 clearfix">
						<div class="nav-btn pull-left">
							<span></span>
							<span></span>
							<span></span>
						</div>
						<div class="search-box pull-left">
							<form action="#">
								<input type="text" name="search" placeholder="Search..." required>
								<i class="ti-search"></i>
							</form>
						</div>
					</div>
					<!-- profile info & task notification -->
					<div class="col-md-6 col-sm-4 clearfix">
						<ul class="notification-area pull-right">
							<li id="full-view"><i class="ti-fullscreen"></i></li>
							<li id="full-view-exit"><i class="ti-zoom-out"></i></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- header area end -->
			<!-- page title area start -->
			<div class="page-title-area">
				<div class="row align-items-center">
					<div class="col-sm-6">
						<div class="breadcrumbs-area clearfix">
							<h4 class="page-title pull-left">Dashboard</h4>
							<ul class="breadcrumbs pull-left">
								<li><a href="{{ url('/home') }}">Home</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6 clearfix">
						<div class="user-profile pull-right">
							<img class="avatar user-thumb" src="{{ asset('backend/assets2') }}/images/author/avatar.png" alt="avatar">
							<h4 class="user-name dropdown-toggle" data-toggle="dropdown">{{ auth()->user()->name }} <i class="fa fa-angle-down"></i>
							</h4>
							<div class="dropdown-menu">
								<a class="dropdown-item" href="{{ url('/change-password') }}">Ubah Password</a>
								<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>
								
								<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									@csrf
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- page title area end -->
			<div class="main-content-inner">
				<div class="row">
					<div class="col-12 mt-3">
						@yield('content')
					</div>
				</div>
			</div>
		</div>
		<!-- main content area end -->
		<!-- footer area start-->
		<footer>
			<div class="footer-area">
				<p>© Copyright 2020. All right reserved.</p>
			</div>
		</footer>
		<!-- footer area end-->
	</div>
	<!-- page container area end -->
	
	<!-- jquery latest version -->
	<script src="{{ asset('backend/assets2') }}/js/vendor/jquery-2.2.4.min.js"></script>
	<!-- bootstrap 4 js -->
	<script src="{{ asset('backend/assets2') }}/js/popper.min.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/bootstrap.min.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/owl.carousel.min.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/metisMenu.min.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/jquery.slimscroll.min.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/jquery.slicknav.min.js"></script>

	<!-- others plugins -->
	<script src="{{ asset('backend/assets2') }}/js/plugins.js"></script>
	<script src="{{ asset('backend/assets2') }}/js/scripts.js"></script>

	
	{{-- Other --}}
	<script src="{{ asset('backend') }}/datatables/datatables.min.js"></script>
	<script src="{{ asset('backend') }}/lightbox2/js/lightbox.min.js"></script>

	<script>
		$(document).ready(function () {
			var flash = "{{ Session::has('status') }}";
			if (flash) {
				var status = "{{ Session::get('status') }}";
				swal('success', status, 'success');
			}
		});
	</script>

	@yield('script')
</body>

</html>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        @if(Auth::check())
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('user.png') }} " class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ \Auth::user()->name  }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>


        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
            </div>
        </form>
        <!-- /.search form -->
        @endif

        <!-- Sidebar Menu -->
        @if(Auth::user())
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">ADMIN MENU</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <li><a href="{{ route('category.index') }}"><i class="fa fa-bars"></i> <span>Category</span></a></li>
            <li><a href="{{ route('product.index') }}"><i class="fa fa-cube"></i> <span>Product</span></a></li>
            <li><a href="{{ route('confirmAdmin') }}"><i class="fa fa-dollar "></i> <span>Konfirmasi Pembayaran</span></a></li>
            <li class="active"><a href="{{ url('/order') }}"><i class="fa  fa-exchange"></i> <span>List Order</span></a></li>
        </ul>
        @endif

        @if(Auth::user())
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">CUSTOMER MENU</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="{{ url('/invoice/list') }}"><i class="fa fa-reply"></i> <span>List Konfirmasi Order</span></a></li>

        </ul>
        @endif

        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li class="active"><a href="{{ url('/') }}"><i class="fa fa-bank "></i> <span>Home</span></a></li>

            <li>
                <a href="{{ url('/shopping-cart') }}"><i class="fa  fa-shopping-cart">
                    </i> <span>Shopping Cart</span>
                    <small class="label pull-right bg-maroon-active">{{ count(Cart::content()) }}</small>
                </a></li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-th"></i>
                    <span>Category Product</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    @foreach(\App\Category::all() as $category)
                        <li>
                            <a href="{{ url('product/category/'.$category->slug) }}">
                                <i class="fa fa-circle-o"></i>
                                <span>{{ $category->name }} <small class="label pull-right bg-maroon-active">{{ $category->products()->count() }}</small></span>
                            </a>
                        </li>
                    @endforeach
                </ul>
            </li>




        </ul>
            <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/sidebar2.blade.php
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
	<div class="scrollbar-inner">
		<!-- Brand -->
		<div class="sidenav-header  align-items-center">
			<a class="navbar-brand" href="javascript:void(0)">
				<img src="{{ asset('frontend/logo.png') }}" class="navbar-brand-img" alt="{{ asset('backend') }}" style="max-height: 65px !important;">
			</a>
		</div>
		<div class="navbar-inner">
			<hr class="my-3">
			<!-- Collapse -->
			<div class="collapse navbar-collapse" id="sidenav-collapse-main">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/home') }}">
							<i class="ni ni-tv-2 text-primary"></i>
							<span class="nav-link-text">Dashboard</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/pos') }}">
							<i class="fa fa-shopping-cart text-success"></i>
							<span class="nav-link-text">Point of Sales</span>
						</a>
					</li>
				</ul>
				<hr class="my-3">
				<!-- Heading -->
				<h6 class="navbar-heading p-0 text-muted">
					<span class="docs-normal">Master Data</span>
				</h6>
				<!-- Nav items -->
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/category') }}">
							<i class="ni ni-settings-gear-65 text-primary"></i>
							<span class="nav-link-text">Kategori</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/product') }}">
							<i class="ni ni-bag-17 text-orange"></i>
							<span class="nav-link-text">Produk</span>
						</a>
					</li>
				</ul>
				
				<hr class="my-3">
				<!-- Heading -->
				<h6 class="navbar-heading p-0 text-muted">
					<span class="docs-normal">Transaksi</span>
				</h6>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/order') }}">
							<i class="ni ni-delivery-fast text-primary"></i>
							<span class="nav-link-text">Data Pemesanan</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/pos/data') }}">
							<i class="fa fa-shopping-cart text-success"></i>
							<span class="nav-link-text">Data POS</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url('/confirmAdmin') }}">
							<i class="ni ni-money-coins text-primary"></i>
							<span class="nav-link-text">Konfirmasi Pembayaran</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</nav>

resources/views/layouts/sidebar_customer.blade.php
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        @if(Auth::check())
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ asset('user.png') }} " class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ \Auth::user()->name  }}</p>
                    <!-- Status -->
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>


            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
                </div>
            </form>
            <!-- /.search form -->
        @endif
    <!-- Sidebar Menu -->
        @if(Auth::check() and Auth::user()->role='customer')
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">CUSTOMER MENU</li>
                <!-- Optionally, you can add icons to the links -->
                <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Tes Menu Customer</span></a></li>
                <li class="active"><a href="{{ url('/invoice/list') }}"><i class="fa fa-link"></i> <span>List Pesanan Anda</span></a></li>
            </ul>
        @endif

        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li class="active"><a href="{{ url('/') }}"><i class="fa fa-link"></i> <span>Home</span></a></li>

            <li><a href="{{ url('/shopping-cart') }}"><i class="fa fa-link"></i> <span>Shopping Cart</span></a></li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-th"></i>
                    <span>Category Product</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    @foreach(\App\Category::all() as $category)
                        <li>
                            <a href="#">
                                <i class="fa fa-circle-o"></i>
                                <span>{{ $category->name }} ({{ $category->products()->count() }})</span>
                            </a>
                        </li>
                    @endforeach
                </ul>
            </li>




        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>